use_frameworks!

target 'NiceThings_Example' do
  pod 'SwiftLint', '~> 0.40'
  pod 'NiceThings', :path => '../'

  target 'NiceThings_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
