# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12
language: swift
xcode_workspace: Example/NiceThings.xcworkspace
xcode_scheme: NiceThingsIOS_Example
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone SE (2nd generation)
podfile: Example/Podfile
#script:
#  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/NiceThings.xcworkspace -scheme NiceThingsIOS_Example -sdk iphonesimulator14.0 ONLY_ACTIVE_ARCH=NO | xcpretty
#  - pod lib lint

