# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12
language: swift
xcode_workspace: Example/NiceThings.xcworkspace
xcode_scheme: NiceThingsIOS_Example
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone SE (2nd generation)
podfile: Example/Podfile
script:
  - set -o pipefail && xcodebuild build test -enableCodeCoverage YES -workspace Example/NiceThings.xcworkspace -scheme NiceThingsIOS_Example -destination platform\=iOS\ Simulator,OS\=14.0,name\=iPhone\ SE\ \(2nd\ generation\) | xcpretty
  - set -o pipefail && xcodebuild build test -enableCodeCoverage YES -workspace Example/NiceThings.xcworkspace -scheme NiceThingsTvOS_Example -destination platform\=tvOS\ Simulator,OS\=14.0,name\=Apple\ TV | xcpretty
  - set -o pipefail && xcodebuild build test -enableCodeCoverage YES -workspace Example/NiceThings.xcworkspace -scheme NiceThingsMacOS_Example | xcpretty
  - pod lib lint

