# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

# osx_image: xcode7.3
# language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/NiceThings.xcworkspace -scheme NiceThings-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
osx_image: xcode11.6
language: swift
xcode_workspace: Example/NiceThings.xcworkspace # path to your xcodeproj folder
xcode_scheme: NiceThings-Example
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone SE (2nd generation)
podfile: Example/Podfile
